class Solution:
    def numSimilarGroups(self, A: [str]) -> int:
        parent = {item: item for item in A}

        def union(a, b):
            x = find(a)
            y = find(b)
            if x != y:
                parent[x] = y

        def find(item):
            if parent[item] == item:
                return item
            parent[item] = find(parent[item])
            return parent[item]

        def is_similar(a, b):
            if len(a) != len(b):
                return -1
            diff = 0
            for i in range(0, len(a)):
                if a[i] != b[i]:
                    diff += 1
            return diff == 2 or diff == 0

        for i in range(0, len(A)):
            for j in range(i + 1, len(A)):
                if is_similar(A[i], A[j]):
                    union(A[i], A[j])
        count = 0
        for key, val in parent.items():
            if key == val:
                count += 1

        return count


A = ["hbnfhxdlatzg", "fzthgahlbxdn", "fbhaglznhtxd", "xgafzhhdlbtn", "nalbhgdxzfht", "nlzbthdgahxf", "nhxahftzdblg",
     "ntbadgxzhflh", "bfxdhzantlgh", "xnlhfgatzbdh", "anhtdzgbflhx", "lbhtdhzfxnag", "xzdhntgblahf", "gfalxnhdzhtb",
     "dbhaltxnhgfz", "hazflhnbxtgd", "tbdhzhlfganx", "tzanhbflhdxg", "ngtbflzdhhxa", "axlhnhbfztgd", "agzhhnbfdtxl",
     "gtadbzfhhlnx", "xhhbtazdnflg", "hdgzfalbxthn", "fhnhbxltzadg", "ngzalfhtxdhb", "hbzxtghfdanl", "hfntlbxghadz",
     "dfhbhzntaxlg", "fblxahnzdght", "xandzlthfghb", "fxdnahzbghlt", "hhdafxnlgzbt", "xhazhnfgtlbd", "nzgtbdaflxhh",
     "hadtxzgbhnfl", "taxdhbzhnglf", "hdzlnftgxbah", "ftzdbhglhnxa", "fdghaltxbzhn", "ahbxgnzhtdlf", "hxdbfhltangz",
     "lbzadhntfxgh", "xnhdhlgtfbaz", "ldazfghbxthn", "xflzgbhhadnt", "lxdafhzgtbnh", "xalztngfbdhh", "btdzlfxghahn",
     "dghzhalbxtnf", "tdlzfnxhhgab", "xltfhnzbdagh", "thgznalfbhdx", "xbthhznfdlga", "dlazhgbtxfhn", "xnadhlgtfbhz",
     "lfbhangdzthx", "xbhfagltnzhd", "hznxbfhagtdl", "zhahbdtnlgxf", "ahdfltzbhnxg", "htalzhxgbfdn", "dbgzlnfhhtax",
     "gaxbhzlhntfd", "htzxfbhgdlna", "fhdtanlzbghx", "tlfgdnhxzbah", "hfhbxztalgnd", "nxftdahlgzbh", "zxghdlnhatfb",
     "bghhxalzdtnf", "hadftbzlnxgh", "zlhhgdbxftna", "hzxnbdfhglat", "dnxzhghabltf", "xbgtldnfazhh", "dnhgbhlxaftz",
     "zalbhtxhdfgn", "dthbxghnzalf", "glxhabndhtfz", "xbhngzlathdf", "hnzxbldfgath", "dlxfbazgthhn", "fnbgxhthzadl",
     "tzglhhxnfabd", "hnalfbdzgthx", "blagxhdtzhfn", "xafgtnlhzbhd", "hbzfldhntxag", "bahhflzxntdg", "zhdtahlfbgxn",
     "hnaldzfhtxbg", "atdzgnblxhhf", "nzhbgfltdaxh", "fadtgbhnlxhz", "lbxgzhthdafn", "ldhzgbaxntfh", "afxlntzbhgdh",
     "fdthgxlbznah", "hxfgtdblzahn", "xflzgbhnadht", "ahfztbndxhgl", "hxfbdhltanzg", "hafghbxnltdz", "hatgxbhfzndl",
     "hhtbdxanflzg", "xlazthhfngdb", "azxlntfbhgdh", "gdtnfhzabxlh", "hzanghxldbft", "xtdlbnfgahhz", "zfagthhdnxbl",
     "xzlbthgahfnd", "adzhnflghtxb", "zhgfandthlbx", "gnxlfhatzhdb", "bghhzlftaxdn", "xfgbzntlhhad", "xnhflbhgzatd",
     "fxntgdlzabhh", "dlxhbngtzhaf", "lxhzthbfngda", "tfxlnazbhgdh", "zgdlnbatxhfh", "dlxhnzbahfgt", "lhbtdxaznghf",
     "tgnzhxfhladb", "blfntdhgzhxa", "hnxfhbatgldz", "thzdahxnlfbg", "xthabflngdhz", "zgbaltnhfhdx", "gfbnzhahdxlt",
     "xgthhfblnzad", "lagzxdhnbfht", "hthzgdxafnlb", "alzhtdnhbgxf", "hgzdnhbaltxf", "fnalzhxgbhdt", "hldbnagtxhfz",
     "abhlhxgntdfz", "ngbxtfzhalhd", "abtlhxgnhdfz", "fhhngaxzldbt", "xgbaznhftdlh", "dbnftxhlahzg", "hlganhxdfbzt",
     "lzgtbdafnxhh", "xdtfnhlzhbag", "zdhfntlxhbag", "azxhtlnghbfd", "hnbxfzgltdah", "bflxdtahhnzg", "xatbzdhfhngl",
     "xtlzadnfhgbh", "hgxndabzlfth", "gblaxzhhtndf", "ngzlbdhxtfha", "hgdxhtfanlbz", "hbgznxtldafh", "hngbaltzfxhd",
     "fdatlznbhhxg", "hhdnbzalxftg", "xndzgabfthhl", "nazlghbxtdhf", "glznahfhxtdb", "nhtgabhdxflz", "zhgabtldnxhf",
     "afnbdgzhlthx", "aghdbtlzfnhx", "hgthdnzfxlba", "lhhtbfzdaxgn", "btdnhxzfghal", "lnafgtdbzxhh", "tbfxhdgzlahn",
     "dxhtfzblganh", "blhxzagtfnhd", "lhhtdfgzxban", "xghdznblatfh", "hznbxldhafgt", "tzhdfbxlagnh", "bndfhtzlaxhg",
     "tgxhhfbanlzd", "fhdtanzlbghx", "hnhtgadzlfbx", "axzlnthdfghb", "dftghnbhxazl", "tbhdhfglxanz", "xlatbhfnhzgd",
     "dhhxabzfgntl", "bghhzaftlxdn", "bazfnlgxhdht", "hnxfhbltgadz", "anflbhxgzhdt", "hfblanhdgxzt", "bdhxtlzhfagn",
     "gthxdfnzhabl", "lfhdxbngztha", "fbxldghnztah", "nfhhgdtlbaxz", "ahbdflghntzx", "hadftbzlhxgn", "hlfdhgzbatnx",
     "zflhxgbnthda", "htfdzblhnaxg", "znldbthghfax", "zhbfdagnxtlh", "hgandztfbxlh", "bltfghndzhax", "abtghhdfnlzx",
     "nhlhftbxgdaz", "hdhxlafntgbz", "tnafblhdhzxg", "nhhfltxdbagz", "nhgtabhdxflz", "fdlngzxhabth", "xhgnfztdhlab",
     "bxtnglazfhhd", "bfahnglxztdh", "bhldntzahfgx", "flbxzahgdhtn", "aztbhgxlfhnd", "axbzlhdfnthg", "tzghlfxnhabd",
     "lhfbzdathxgn", "lzxgndfhthba", "tfbxhdgzhlan", "hbflgaxzdhtn", "tlgxdnfzhabh", "tzfbaglxhhnd", "fatdhgxnlhzb",
     "zhbdgxhfalnt", "hdhblafntgxz", "ngzlbfhxtdha", "zblhxgfnthda", "dahbthzlxgfn", "hxhfnadbzgtl", "nhtahxdgblzf",
     "xzdfnghlathb", "dxahflzgtbnh", "lthzabdhgnxf", "adnhzflghtbx", "gbxzhtalhdnf", "zfahbngdlhtx", "zxhhbgandlft",
     "htzxbfhgdlna", "atflhgxhndzb", "hgzhtnaxdflb", "lhtfgdanxzhb", "xnhbaztdlfgh", "nfhzatlgxbhd", "htfdzhlgnaxb",
     "zanhdfhtlgxb", "dxatznhhglbf", "bhdaxlfhgtzn", "naghxhlfdbzt", "hfhtxzgalbnd", "gtxnlhdabfhz", "zlghbdtfnhxa",
     "lhbhzxgntdfa", "hdlhxntgazfb", "ahxhtldfznbg", "bltdzgfnhahx", "bzhgtxfnlhad", "lbnxhgfthdza", "nhtbfhzaxgdl",
     "xfzlnbghtadh", "fhdzbxntlhag", "tbfxhdgzlhan", "xfhnalgzhtdb", "lhtazgnxfbdh", "ghbtdzfhxlan", "hgdhtlbxznaf",
     "xalnhftzbghd", "xbtlhagnhdfz", "xnhflghbdtza", "thxdaflgbznh", "hatndxzgbhlf", "lfxnzdaghhbt", "hbzxtghfdaln",
     "afthgldxbnhz", "tbgzhlxhfand", "lhnfabhdtgxz", "hafghzxbltdn", "nabdxzglfthh", "thnfabhdlgxz", "ghndtfbhazxl",
     "lzgabdntfxhh", "falbhtxhdzgn", "ltadfzhbghnx", "xahgfbnldzth", "hthzgdlafnxb", "ghbznxthlfda", "glafxbndhthz",
     "ltfbgxhdzhna", "zxhgbltdfanh", "lxfbzhagdhnt", "xhzhbagtldnf", "glxhhatfdznb", "gxhthdflbnza", "htfdzblhxang",
     "gaxzltdnfhbh", "tadlnhxgzbfh", "fblaghznhtxd", "glhnbatfdhzx", "fbltahnzdghx", "fghztnhdlxab", "tfzdhnhgbxal",
     "gldbhznftaxh", "lngfhdtzabhx", "axbzlgdfnthh", "zltfhaxhbngd", "tglzxnafbdhh", "xabtlgndhzhf", "gbnxhfdhtzla",
     "hzanghxdlbft", "tnhbazxdlfgh", "xlazhhtfngdb", "xgdhznblathf", "txzhabdglnfh", "nhfhgltzbdxa", "dbnalfxghzht",
     "hgxfntlbadzh", "nbxgzhadhltf", "txhahnblzdgf", "xhfdltzbghna", "hhazblfngtdx", "zxldahntghbf", "bfhhdngtaxzl",
     "bhgalhfxtndz", "hndgxlatfzbh", "gltndhxfzbah", "gdhnzlbtfahx", "hxfbzhltangd", "hdtglnbhxfza", "xzfnalgtdhhb",
     "tlagnfhhbdzx", "gabtxzhnlhdf", "nzlxhaftbdgh", "nhhtxzdafglb", "zxldahgtnhbf", "hdbtlfxzghna", "ntazbdlhhfgx",
     "ltdhbangxhfz", "agnlhtzdxfhb", "tnbdhhalgfzx", "adzhnflghtbx", "gabhxfnlhdzt", "angzhxhfdbtl", "gfdtaxnlzhhb",
     "hafdtnzlbxgh", "dghthzbnaxlf", "zbhdgxhfalnt", "tfbhghazlxnd", "lthdabzhgnxf", "hflxhbgntdza", "fgtadlhbhzxn",
     "ngxfhdthalzb", "hgdhanflxztb", "hzahblfngtdx", "fzxanghltbdh", "dazfhgtblhxn", "hfxtbznghadl", "gdtnfhzlbxah",
     "dahxthzlbgfn", "ahnbdtxghlfz", "gtahhbfdzlnx", "hgdxhtfalnbz", "nbxdahzghlft", "tbahhngzflxd", "tzganhldfbxh",
     "alxhntghzdbf", "xghdahtbnzfl", "zdhfnhlxtbag", "fatgldxnhhzb", "hflzghntbadx", "nabtxzglfdhh", "dbfalthnxghz",
     "xbhfaglhnztd", "txzhbdaglnfh", "ltdbganxzhfh", "ahfbnhxtdglz", "hxfgtabldzhn", "bnzfatdlxhhg", "nhdtalzghxfb",
     "tahngxhblzfd", "hhnzabtdxgfl", "gtadbzlhhfnx", "dtzxhnhbalfg", "axhdgflbzhtn", "hhgnfbtdxlaz", "znbhxahtlgdf",
     "axzhdltnhfgb", "tagfbhzndxhl", "htzxbfhgdanl", "tghlfnbdahxz", "zldngabhxhft", "lhdzangbxfth", "fdhnthxzbgla",
     "fhnzhlbdatgx", "gtxhlbahdzfn", "fdznglhbaxth", "xbhhdaftlgzn", "thnhxldzafgb", "hdbtlaxzghnf", "tgzfbhandxhl",
     "hzbgtxhfdaln", "bhafxldntgzh", "hbzthdngaxlf", "bxtzndhlaghf", "xdthnlbfzgah", "blagxhdtfhzn", "bgzxadhlntfh",
     "bhnahxdgftzl", "agblhtzdxfhn", "fbxdtghnzhal", "gbzxatdhlfnh", "lathzgnxfbdh", "lzgadhfbxnht", "btaxlgndzhhf",
     "hxfgtdblazhn", "tgnhhxfzladb", "blfhxaznhgdt", "nzlxhbftadgh", "thxbnazdlghf", "lxtdanhfzhbg", "dlgnbhfahxtz",
     "ldhnzgbtfahx", "fadhngbhxltz", "hdagbxlthfzn", "hbxnghtfladz", "lbfgzhnhdaxt", "lnbhadxthgfz", "bfdzhanxhgtl",
     "dlhanbgtxhfz", "zhbftlhdganx", "gfdhtlzabhxn", "tnfbazxdlhgh", "zgdltbaxnhfh", "ztbadhhlgnfx", "tgxhhfblnzad",
     "txbnzfahghdl", "hdnhxltgazfb", "hhaftdzlgxnb", "ndzghhbaftxl", "xhtlzfdhabng", "fhganltxdbzh", "hxbnzfatghdl",
     "hxtzbdhlafng", "bhnaxlfhztgd", "zdxltgnhahbf", "abhnhflgzdtx", "xhflndzhatgb", "tnhagldfxbhz", "fxdbghntzhla",
     "lzhbgfntdaxh", "falnhtxhdzgb", "lzxfhtbaghnd", "zgdlnbaxthfh", "dahxghzlbtfn", "btfzdgxlnhha", "hfthznglaxbd",
     "bxztldanhghf", "xgbatfnhdzlh", "ndhtfgalbzxh", "fztanghlxbdh", "fbhnxzdtlhga", "fnhlhazxbtgd", "flthdbgznxha",
     "hlfdhgzbntax", "bhnazgdlxthf", "hafdtbzlnxgh", "hlnhfazdxgtb", "dtlfazghhxbn", "ghbhtfanlzxd", "dztbhgxlfhna",
     "faxzntgblhhd", "flhhdbgzntxa", "glznhhfaxtdb", "thdglhaxfznb", "hngdtxbazlhf", "nhdfalzghxtb", "glhnbatfzdxh",
     "hlabndgtxhfz", "zbalgnhtfdxh", "thzdhaxnlfbg", "gahbfhzxndlt", "lanzgdhbhtfx", "dltzhgbaxfhn", "txlhnfadbhgz",
     "haftzbnlhxgd", "bhhxladgzftn", "lhzatdfbxhng", "thflgazxhdbn", "lxhhaftzbdgn", "tzghlhxnfabd", "thfndblhxazg",
     "dhhnzbxfagtl", "zxblndthfgha", "gzblnfadthxh", "ghlazntfdhbx", "afnbdglhzthx", "bngtahlfxhzd", "lxhnhdzbgatf",
     "nhbhzlxtdgfa", "hfgdhalbntxz", "btnhgfxazldh", "fnzhhglxabdt", "txhlnfdhzabg", "lhbnadfgzxht", "hgdxafbzlhnt",
     "adxzhlgfnhtb", "hxzdtnghflba", "zahbhglxdnft", "bxadhhgtnlzf", "hxblanhdgfzt", "gxltbfzanhdh", "thaldfbzghxn",
     "hhdnbtalxfzg", "ftdghzbnaxhl", "bazdhlgxnfht", "hxdahzgtlfbn", "btghdlnfxzah", "anhbtzglxfdh", "xtbzafndlghh",
     "ztbadhhlgxfn", "axzflgdbnthh", "lagzxbfhtndh", "lnzgahfdbthx", "tlhgfnbdahxz", "dbxthzalnfgh", "fanhzbxgdhlt",
     "lxagfhzdtbnh", "dxnbglzfhath", "gazhxfnlhdbt", "bflhzanxhgdt", "gflnxzhdthba", "tdhgbnahzxlf", "ahlfxgtbhznd",
     "taznldhhxfgb", "zhgfnldtaxhb", "xgdtbnlfhzha", "hnltbzgxfdah", "nhdzflagxbth", "lztfahxgndbh", "ndlhxbghfzat",
     "nahbhgdxzflt", "dbnalxtghzhf", "nthahxdgblzf", "adxzhhgfnltb", "fgnhbdatxzlh", "nxhlhfagdbzt", "gzhtdfxalnhb",
     "tzabhglxfhnd", "nzhldtaxbhgf", "zdxtnlfghhba", "fhltagbdznhx", "htznxgdhfalb", "gbfnhtdhalxz", "dxfanglhtbhz",
     "dnxtfhzghalb", "xlhbtfhnagdz", "hdhxzafntgbl", "gdtafxzhnbhl", "xghdlhtbnzfa", "abxzlghtfdnh", "fhnxhlbdatgz",
     "fxzlthabndhg", "hbzfhdngaxlt", "fnhhgdtlbaxz", "gbltxdfzahhn", "axbflgdznthh", "xdabltfhhgzn", "xhazbdnlghtf",
     "zgxfnhthblda", "axhngbtdfhzl", "nldxfabhzthg", "hxdznabtflgh", "xalfdntgbhhz", "tbzhalhdxnfg", "zfbhangdlhtx",
     "gblaxdfztnhh", "hztnlhgbdafx", "gzndxhahfltb", "zbnhtfgxahld", "azlhgfbdnthx", "fbxldghnzhat", "nbxdlhzghaft",
     "bdfgztlhnxha", "hnzltgaxdbfh", "hdhzltaxgnfb", "xgafzhhldbtn", "btghdfnlxzah", "fhzdnbxghlta", "fzhdlxabnhtg",
     "zflabthnhdgx", "nbgxatzhdfhl", "hlztndfxahbg", "ndxhtbhzfalg", "hbnfxlhdztga", "lfdgtbxnazhh", "faghxdnthlbz",
     "angtdzhbflxh", "hghbxnlzdtaf", "dgnftxhlahzb", "tazdhngxhblf", "ahzxfgnlhtdb", "gbafzxdhlnht", "zlxdtghnfhba",
     "htznxgdlfahb", "dbhfhzntaxlg", "fthbxghnzald", "htgnzbxfhdla", "hnadhlgtfbxz", "lfbzdnhgxaht", "tgndhxfhlazb",
     "glzhhnfaxtdb", "tdhfhnzlbgax", "fadbgtnxzhlh", "lntfhdgzabhx", "hfxtlznghadb", "bhztdagxfhln", "adhtzlhgfxnb",
     "gazhxlnfhdbt", "naxzgblfdthh", "hdxlnftgzabh", "ahnbxtdghlfz", "hlahntfzgdxb", "hafghzxnltdb", "btahhgfdzxnl",
     "gzxbfhndltha", "hafghznldtbx", "htdhgfnlabzx", "hgztndhalxfb", "ngdxlzhbhfat", "zgdlhbatxhfn", "zlngfaxhdthb",
     "bdxtnfahhgzl", "dthzhalbxgnf", "hxblafhdgnzt", "hdtbfxazlhng", "txdznfgblahh", "bhgtdfnlxzah", "gbhtaxhndzfl",
     "hdlbfhaxzgtn", "dfnghzltbhxa", "ghzlanbthxfd", "hlgdtxabznhf", "tgzbfhandxhl", "zahbnfgxdlht", "hzgdlhtxnbfa",
     "thxglzdnhabf", "xthzadnflgbh", "fatdlgxnhhzb", "tgzdnhbalhxf", "afdtgbhnlxhz", "hgzflhnbxtad", "hghtdzbnaxlf",
     "bgtzahflxhdn", "ngdhfazltbhx", "ltdbzhnxfagh", "hahtxzgbdnfl", "hgxhtdbanlzf", "htafnxzhlgbd", "adzhnblghtxf",
     "zgxfnhthbdla", "dntxgzhhalbf", "abzhtdnhlgxf", "tzdhlfxnhabg", "fxzgdbatnlhh", "zhghdlbntxaf", "xzghabthlndf",
     "ahxhbgfltdnz", "hdfazghlxtbn", "gflnxztdhhba", "tgahdbxlhfnz", "hfhatldnxzbg", "hnzlbtgxfdah", "ztfhnxldhgab",
     "dhnlbhtzfxag", "hatndxzbghlf", "lnhbhxdgzatf", "lfxnztbhhagd", "adhblhfntgxz", "hnzxgldfbath", "hxnbtdaflzgh",
     "axhtgbndzhfl", "xzgtldnfabhh", "ldtaxfgbnhhz", "gatnfhhxbzdl", "nxftdahzglbh", "ndfthalhgzbx", "gafhhzxbltdn",
     "gxztbanhhfdl", "blzhathfdgnx", "hzanxhgdlbft", "nfagtxdlhbhz", "dznlfhaxtbgh", "ndhzahftlbgx", "xahztldfnhgb",
     "agzhdltxhfnb", "nzxhdaghbtfl", "zhganltxdbfh", "hzhfnadbxgtl", "fdhnthxzbalg", "hdtxlznaghbf", "bzaxlgndthhf",
     "naxzglbfdthh", "hgnzbftadhxl", "ahxfzlghtbnd", "hnbxdzgltfah", "nbhdgxhfalzt", "dhxlfhzgnatb", "tnaxfdglbhhz",
     "bhlxdtafhnzg", "nxghhlbdzatf", "xfagtndhzbhl", "zlthbdgfnhxa", "hhaxntbdfzlg", "bghdlatfnzhx", "hnfbzgtdlaxh",
     "hnalzhxgbfdt", "dlagtnxhfhbz", "ftaghzdxhbnl", "lxanhtzhbfdg", "bhatglhxzdfn", "xtbzadnflghh", "lbxadfghhztn",
     "hzghbnaxdflt", "lahhtdnzbgxf", "hngdtxbazfhl", "zanfbhxlthdg", "nhdtaxbfzlhg", "gntdhhfazblx", "ghbhadtfnlxz",
     "lhatdfgzhbxn", "nhglabhdxftz", "hlnbtdafxzgh", "hzlhfbnxdgat", "hazlghbxtdnf", "xhtlzhgndfab", "hxdgfhltanbz",
     "xhazbdnlthgf", "bhnxlhafdgtz", "dgfnltzhabxh", "ngxadltzhhfb", "xlzahgnthdbf", "hgadbflzhtnx", "lgdbzhnxfath",
     "xhtdgafznhlb", "lfdtgbhnaxhz", "hfzltgaxdbnh", "ltzhdfnaxghb", "lhdbgxnzfhat", "hxhbdlztagnf", "abfghtzhlnxd",
     "nzhlgfbtdaxh", "balhdtzxgnfh", "zxtlhdhgfbna", "bzhfgtdxlhan", "bnzhatdlxhfg", "gltzfhaxbdhn", "xdhfnhlztbag",
     "xhfzhnagtlbd", "dbgzfnlhhtax", "lhztadfbxhng", "hdnlazxfbhtg", "zghftbahxlnd", "xfbgaldnhzht", "fdhbxthnzalg",
     "ndxhtfhzbalg", "nxhaldtbgfhz", "lhabdxhztfng", "txzhdbaglnfh", "gzahlhtbfdxn", "hlxbndgathfz", "hxdgbfzatlnh",
     "fdtabhngxlzh", "xatbzghfhndl", "hzhgdalfbxnt", "lnxhadbthgfz", "xnazfhhgtbld", "nfhladtbgxhz", "gblfxthnahdz",
     "bzahtlgdnhfx", "ndahtbhzfxlg", "hdlhzagftnxb", "habtxzhglndf", "tfhnzdagbxlh", "dthxbzahlngf", "zbhahdglfnxt",
     "hgtxzfhnabld", "bgxfnthldhaz", "zlxbhdnhatgf", "gfdhtlzabhnx", "ghbntxflhzad", "gaxhltdnfhbz", "ldhzgbatnxfh",
     "daxthbzhnglf", "bldzxhghnatf", "lzfabdntxhhg", "xafgnhdthzbl", "bzhgtxfnhlad", "btzhgfxahldn", "bthzlfxghadn",
     "lxahnhgbtdfz", "flthxadzbhgn", "nhltfhbxgdaz", "htdafxhbgznl", "hgdhanlfxztb", "hdnazghlxtbf", "gbfzhtdhalxn",
     "nhlhftaxgdbz", "hxfgtzbldahn", "tlfganhhbdzx", "ahzxltdgbhfn", "hnazhgbdftxl", "tdnfahbxzlhg", "dhxtanhglbzf",
     "nfhaldtbgxhz", "nglbxhtfhadz", "fadglhzxbthn", "tlabhzxhdfgn", "nbhxlgftdahz", "afnbdglxzthh", "tgablhzfnxdh",
     "tngfhhldzaxb", "hghbxalzdtnf", "xhbtnzldghfa", "xdfbzghnahtl", "gdtnhhzabxlf", "lbdgxfzthahn", "tfblnazxhgdh",
     "bxztadlnhghf", "tnhfblhdazxg", "langhdzthbxf", "atzlnxhgfdhb", "xhatglhbzdfn", "hhazdtnxblgf", "bdfztgxlnhha",
     "glhhaztbfdxn", "bldzghxhnatf", "abzftdlnhxhg", "hhldngabtzfx", "ztgfhndhaxbl", "xfdgalbnhzht", "ghntxfzdlbah",
     "nldtbfahghzx", "hlztngfxahbd", "ftxzhgnbldah", "zlxgndfhthba", "ldtzabnhxfhg", "lngbhdtzafhx", "hxagzfbhdtnl",
     "fdtalgbhnxzh", "tlngafhhbdzx", "dhtnxghlazbf", "hzgdnbfxalth", "hfhgxztalbnd", "hanxdhztlfgb", "fndlbhtzgaxh",
     "ghazlxdftnhb", "dlhgfnbtahxz", "dhbhaztfnlxg", "ntadbzlhhfgx", "fhazlxdgtnhb", "fxzgdbntalhh", "bltfzhndghax",
     "dtlhangzxhfb", "hlhztnxgdabf", "ftzgadhxlnhb", "hlnfgthadzxb", "hnhagldfxbtz", "anhflbhgdxtz", "zlabhtnxgfdh",
     "hxthflbgadzn", "dhtlabhxgzfn", "xahtlgndbzhf", "dahbltgnfxzh", "zhdtahlfbgnx", "fblxdhtngzha", "zhxnalthbgfd",
     "ahhzblfngtdx", "ltdbzhnxgafh", "axlnhhbfztgd", "fxlngbatzdhh", "ahfghznldtbx", "lhtfzdanxghb", "zalfbthnhdgx",
     "ztdlhhngafbx", "tfbhghzalxnd", "flxhdghtbnaz", "ghbtdzlhxfan", "fdtnghzlbxah", "lthxzhngfbda", "nhfxgabdhztl",
     "bfalhzghndxt", "znabhtlxgfdh", "dthxbghnzalf", "zhbdgxhfnlat", "tflzxhdbhgan", "azdhlbtfgxhn", "hztdfbgahlxn",
     "hfntlzxghadb", "lhxtdfgzhban", "alnbhfxhtzgd", "xlazhhtnfgdb", "txzgaflhdhnb", "hlzthdngaxbf", "lzgtbdfanxhh",
     "xhbtnfldghza", "dgtfhnbhxazl", "glfzhtdhabxn", "gahdfhzxnblt", "ldfgztnhbxha", "hbflgaxndhtz", "fhxhdgltbnaz",
     "zdhhbfxatnlg", "hbzftdlnhxag", "hzhbdalfgxnt", "nlhxfabdzthg", "bhafxzdntglh", "nltzxbhgadfh", "hbzfldtnhxag",
     "lfxzgbhnadht", "zfagthhdlxbn", "hbnftxdlahzg", "adgnbxtflhhz", "dhtnxfhlazbg", "fznhbxlthadg", "atdlhgxhnfzb",
     "xzfnalgthdhb", "hzgndbfxalth", "gbdzhfhantxl", "atzlnxhdfghb", "nlhghzaxfdtb", "nzhflhbgadtx", "bhxgzflhtdna",
     "txbngafhzldh", "dbhhltxagznf", "ltadfzhbxhng", "hfbgtdhalxnz", "tdxfhbgnlhaz", "hzgftbahndlx", "zdxltghnfhba",
     "hzhbdagflxnt", "lbxgzhnhdaft", "fzatnhbgldxh", "bxlhnfzatgdh", "nhldxbghfzat", "agthdnzfxlbh", "dzafxlghhnbt",
     "ghhzldtnabxf", "txlbhndgfzha", "fnzhhxlgabdt", "zdafntlxhbhg", "hgdtanlfxzhb", "lfdhxbathzgn", "zfbhangdlthx",
     "gldabhzxfhnt", "danlbhtzfxhg", "hbganztflhdx", "zhbtlgnafhdx", "dgnzhtlhfxab", "lnabhtgfdhxz", "htlaghfdbnxz",
     "ahhzbdfngtlx", "znldbtghhfax", "lbxzhtaghdnf", "abnfxlhdztgh", "dbthlxfhngaz", "htlnxgdhfazb", "axgzfnbhldht",
     "zxhdfabngtlh", "xlhbtazdnfhg", "nhzxltdgbhfa", "nhtbfhzlxgda", "dxfnltzhabgh", "lfdgtbxzanhh", "gzhntdfblxha",
     "ahtnfdzbglxh", "htnfdxlbgahz", "fltxnbhadgzh", "xhtlhagnbdfz", "txbngafhzhdl", "lgadfzhbxhnt", "hagfbtzndxhl",
     "fzdhhbnlagxt", "gafhhtxblzdn", "fdatlznbhhgx", "fbhnxzdglhta", "zghbnfaxdlht", "hlthgandbzxf", "fhxnbtzlhgda",
     "dngfxthlahzb", "glznahftxhdb", "bxahflzgtdnh", "nglxtfzhabhd", "fldtgbhnaxhz", "fnatglbdxzhh", "hdazfglbxthn",
     "tdlhbafxgnhz", "hlbntzfxdhga", "thnhxldzagfb", "lxdgfhzatbnh", "abthznxgfhdl", "tdhfbnahzxlg", "hldanbgtxhfz",
     "gnxflhatzhdb", "xanzgdhbhtfl", "adhlzhgxntbf", "hlgantxdfbzh", "atzxnlhgfdhb", "fdxhaltgbzhn", "hnzxfldgbath",
     "gfhdnbtlxhaz", "glxfabndhthz", "fnlhgdthabxz", "ghbtazlhxfdn", "lhxdhngtzafb", "talbhzxhdfgn", "gfxabnthzhdl",
     "hdfgzhnbtaxl", "alfhxbznhgdt", "lbztdhnafxgh", "lzhbgantdfxh", "ladbgtnxzhfh", "baxghzlhntfd", "xalfdztgbhhn",
     "gdhzltaxhnfb", "zflabthngdhx", "hngzbhdxfalt", "lhfxgabdhztn", "adgnbhtfxhlz", "zthxbnfldagh", "hahbngdxzflt",
     "agdhzhlxnbft", "dgtbxnahfhzl", "ngzhhabfdtxl", "lxagfhhdtbnz", "znfbatxdlhgh", "hnblgaxzfthd", "ndhxlgfbtahz",
     "znbtlhgaxdhf", "ghlzanftdbxh", "nfhhgltdbaxz", "xbhltfhnagdz", "bthhagfdzxnl", "zbhxdnfgtalh", "zlhhgxbdftna",
     "zghlxhdtafnb", "bgztdahfxhln", "lzgtbdnafxhh", "hhltanfbxzgd", "hlhtznbgxdaf", "ghxhbdnazflt", "gatzxhldnhfb",
     "tbndhlfagxhz", "hhfngltzbdxa", "xbgntzlahfhd", "nfxtdahlgzbh", "gnzlbdhxtfha", "fdhntbxzhgla", "dflhnghtxazb",
     "bhflgazxhdtn", "btflgxhdzhna", "zbatgxnhdflh", "fhthbxlnzadg", "bdnazghlxthf", "zxanbhfdhglt", "gfhlxbhdznta",
     "gntdbhfazhlx", "lhafxdnztbhg", "zdxltghnahbf", "hlhntzfxdbga", "lbtzahhdxfgn", "gztfahxlndbh", "lbnghdzahtxf",
     "dhtnxgflazbh", "dahnzgtlfxhb", "hlbfdagtxhnz", "taznfdhhxlgb", "axlfdntgbhhz", "thzdafngxhbl", "fgbnhdthzlxa",
     "dbnalxfghzht", "hdfazghtxlbn", "thnafzbxdhlg", "gtfxalhdbzhn", "gbdzhfhanxtl", "tazbfxhhgdnl", "bhdaxlfhztgn",
     "xfhgzdabhnlt", "hngtbzlxfdah", "bgdnhxzfthal", "btahhgfdzlnx", "nthahxbgdlzf", "fbhnxztdlhga", "lthhfdzbxgan",
     "tnhhdfbalzxg", "tfbxhdgzlhan", "fxhbzgtadlnh", "ghthbdzlaxnf", "balhntzhfgdx", "hngldzfhtxba", "bthhdgxznlaf",
     "hgfaxbtnzdlh", "xghdznblathf", "txhblndgfzha", "anhflbhgzxtd", "hdhlanxfbztg", "dlhxabhgftzn", "nfbldhagtzhx",
     "ngtzxbhladfh", "dfthznglaxbh", "htnlbaxzhfgd", "dghnltzfabxh", "ahngzhbxltdf", "hhaftdzlgbnx", "gntafxzhdbhl",
     "lnhbhxgdzatf", "dbhalthnxgfz", "dbhthzalnfgx", "lfhzgbatnxdh", "lhafthzdnbxg", "dnxlfhzghatb", "dflznghtxahb",
     "bfzanghthdlx", "blhxzantfghd", "fbdzxthhlnag", "gflxhnhtbadz", "ahxfzhndtbgl", "xtdlbhfgahnz", "hdhtganzlfbx",
     "xtadfzhbghnl", "nlghabhdxftz", "zxanthdfhglb", "bdxthzanghfl", "lhxnhtagzfbd", "hafdtnzhbxgl", "ghxtlzdnhabf",
     "nlhgxzahfdtb", "fbzhhdngaxlt", "zxanbhdfhglt", "dngftxhlahzb", "fthzxngdhbal", "dtlhhgbfxanz", "hzanfhxldbgt",
     "hblaghfdtnxz", "hfzntgaxdblh", "blfgnxhaztdh", "lhxnhdagzfbt", "xhgnfbtdhlaz", "bxlhntzafgdh", "fhnxhlbtadgz",
     "bazhxlnfhdgt", "dxbthnlazfgh", "hdbfazxhntlg", "aghlhnzbxfdt", "agzhdltnhfxb", "dabhxzlgnhtf", "hxfgtdblanhz",
     "xghblhtdnzfa", "fbtzgdnaxhhl", "gnhzlfabxhtd", "hhaxntbgfzld", "dxazflhgtbnh", "blfgnxahztdh", "lnhxzfgbadht",
     "thdbnzfahglx", "bdhfxtazgnlh", "gzblnftdahxh", "hbzgtxhfdaln", "lthxhngdazbf", "dgbhaztfnlxh", "nhgdflxabzht",
     "tgdlbnfhahxz", "zlxdbghnfhta", "bathdhglxnzf", "hhtblzgnadfx", "btnhgfxahldz", "nbhfxzdatlgh", "xdgtfzblhanh",
     "fzhnbxlthgda", "tfhgdlznaxhb", "zhbhadtfnlxg", "gzfntbdlxhah", "fngtahlbxhzd", "tzxdhfbhlang", "nbhtxzdaflgh",
     "ltdbzanxghfh", "ahnhfxzbgtdl", "dfxnzgtlbhah", "ndfbzgahxhtl", "dxantlhgzhbf", "bhztdagfxhln", "lztbganhdfxh",
     "fghbznhdlxat", "fghhzabtlxdn", "nldtbfghahzx", "dhhxablfgntz", "hhflntbaxgdz", "ndtgabhhxflz", "bzdfxtaghnhl",
     "axhngbtdzhfl", "ahfztbnhxdgl", "xbdlfgnhatzh", "gbndflxhthaz", "nbxdahzghltf", "alzhhnbfdtxg", "bdatglhxzhfn",
     "lzfntbahgxdh", "xnadhlhtbfzg", "fbghltnxzdha", "flthbdgznhxa", "hzanfhgdlbxt", "hbflzaxgdhtn", "fxtzblndghah",
     "tzlxhdanhfbg", "xbgfhztdalnh", "zdhxbnfltagh", "ahntzhbxlgdf", "fthgdzbnaxhl", "xdhhlngzbfta", "xhbdltzfghna",
     "hlanbdzhxtgf", "nhtgldhabfzx", "lfgnzbdxhtah", "hagtfxhbdznl", "lhxnzdaghfbt", "thbngafxzhdl", "dlhnxtzhfabg",
     "lzfabdntghhx", "nhhdflxabzgt", "flzdanhgtxbh", "bhgfnldthxaz", "ahglzhfndbxt", "hahgfznldtbx", "hlfhgnaxdbtz",
     "bazdnlgxhfht", "fthblnhzdagx", "bnhtldghfxza", "xgdlbnfhahtz", "htghdnzfxlba", "latgfdxnhhzb", "fzhhlxabndtg",
     "lzxfhgbathnd", "zndalbthfhxg", "fldxnbhatgzh", "dxnbglzhhatf", "ahghfxzbntdl", "tngblhzfaxdh", "nzgtbdfalxhh",
     "xfzbgntlhhad", "tbhglhxanfdz", "lgzxhadhtbnf", "nhfladxzhbtg", "hfzntgahdblx", "aldtbfghnhzx", "tgdlfnbhahxz",
     "hgdaxbtnzflh", "ahfhdgbxlnzt", "hhxzdtnablgf", "gnthbdzlaxhf", "nlxdthbhafzg", "ahnthldfzxbg", "hxzlnhftbgda",
     "dlagxhbtzhfn", "fnhhgdtlabxz", "xbgnhzlatfdh", "atnzbhxhldgf", "xdhtfzblganh", "zdaxnfglhthb", "hlnfhazdxgtb",
     "gltzfhnxbdha", "tlbfnazxhgdh", "adhlzghxntbf", "tagblhzfnxdh", "bhahxzndltgf", "zxhhtndfaglb", "baghxfnlhdzt",
     "gxhzldtnabhf", "nzxhgadhbtfl", "gdxfhbtnlhaz", "dgxtalhnbfzh", "btnlgfxazhdh", "fbnzdxhghlta", "hhtblzgnadxf",
     "lnxtbfdagzhh", "hdzlnftgxabh", "lbadnfghzhtx", "zhtnxgfladbh", "bflhhgaxztnd", "txlhbdagznfh", "xndzagbfthhl",
     "nhlhzbxdftga", "ahxfblghtznd", "tbhdhfglzanx", "lxfhahtzbdgn", "btfzngxldhha", "gbzfatdhlxnh", "zlhhnxbdftga",
     "zlthgandbhxf", "nglbxhtfhzda", "fbxdlghnzhat", "bhhxladgtfzn", "nbhtxzdafglh", "xthafblngdhz", "tnfzhhdgxbal",
     "gblaxhfztndh", "lfnahbdhzgxt", "fgaxtnhdlbhz", "flthdbgznhxa", "xdbhnltfzgah", "nxafgbltzdhh", "lbnghdzthaxf",
     "lfdzgbhnaxht", "faxnhghtbdlz", "ahzxfghlntdb", "nhtgadhlbfzx", "tfbzdhhnlaxg", "nfdhgazltbhx", "hxfzhnagtlbd",
     "dnxbfhzghalt", "nfhlhxdzbgat", "dgnzhtlhxfab", "hbxaltgnhzfd", "hzghtnaxdflb", "blfgnxtazhdh", "ghbtnxflhzad",
     "blhxtdzhfagn", "hhtdxbanflzg", "agfznlxhtdbh", "dzxthfbhlang", "fdxntzbghlah", "gblaxdfzthhn", "xdfbtghnahzl",
     "tzhdfbgahlxn", "dfxnzhtlbhag", "tdlzfxnhhgab", "fblzagdhxthn", "gzbnfdlthxah", "halhfbnxdgzt", "htfdzglhnaxb",
     "lnzfhdgtabhx", "hbnaltgxhzfd", "lzfabdntgxhh", "dltbnhghazfx", "nfxadthlgzbh", "lxgnhtazbdhf", "xbgntzlahfdh",
     "bfxhdzantlgh", "hbzxtfhgdanl", "axzlnhftbgdh", "fgzhhxlnabdt", "bhxtdfazghnl", "hhtdbxanflzg", "ndgtxhhbzlaf",
     "gdaftnxhlbzh", "hgdtbnlfxzha", "xhztghlnbadf", "hbgazntflhdx", "ahdnzgbflhtx", "faxbhltndghz", "txzgfalhdhnb",
     "atnxlbhzfhgd", "glxzhatfdhnb", "tgafbhzndxhl", "xnhlhdgtfbaz", "nztblgadhhxf", "bthaxzhndgfl", "fbadtzxhhngl",
     "tghadbxlhfnz", "zhgfhndtaxbl", "lazhtdnhbgxf", "hxdfbaglhnzt", "adxzhlnfghtb", "alnghbhzxdft", "zhnxglhafbtd",
     "hlxbndgtahfz", "hlhantfzgdxb", "nxlfgbatzdhh", "zbxahfldtngh", "flthzadxbhgn", "lhtzhanxbdgf", "zhtnxgfdalbh",
     "fthbxdhnzalg", "aflthxbngzdh", "hahtbdzlxnfg", "fbdhlnaztxhg", "hfndlzagbxht", "fgdalhzxtbhn", "ndabtzlfxhhg",
     "ngxbtdlzfhha", "balhntzxfgdh", "fhgzhbdnatxl", "fdlngzhbaxth", "hfbzldhatnxg", "tfdnzhagbxlh", "zhfbdagnxtlh",
     "hgnfzdhbtlxa", "nhdzalfgxbth", "nfxlbazdhght", "zhgfnldthxab", "dnhgbalxhftz", "danhzlxbtfgh", "hgxhtfbanlzd",
     "tzhbaglxfhnd", "gnhzltabxhfd", "gltafxzhnbhd", "ahnhtldfzxbg", "bhzlxfghantd", "hxfgtdlbanhz", "hxghflbtadzn",
     "xgzhhflnabdt", "adhblhfntzxg", "xhdtgafznhlb", "zaxbhfndlght", "hbdlfgnxatzh", "ndzfahblthxg", "fndzxthhlbag",
     "hltxzfhnabgd", "lfbhdnhgxazt", "htzxfbdghlna", "hgafntlbxdzh", "hlanbdhzxtgf", "blfxhgtdanzh", "gatlzdnhbfxh",
     "nabtxzhglhdf", "fdghabtxlzhn", "lhxhbdnazfgt", "hdafntlghbzx", "btdnhxzfahgl", "xtlznahbfhdg", "bhnxhdgfazlt",
     "xghdznflatbh", "bxtlhazfhndg", "bzaxlgdnthhf", "adgnbxtfhhlz", "alngxzhfthdb", "hldbgznftaxh", "zdafntlghbhx",
     "ghaxfztnhbld", "bnghazxdhltf", "fdlngzhxabth", "alnghbfzxdht", "gxhbfadnztlh", "hlangzxbtdfh", "xzgahbthlndf",
     "hnlzbtgxfdah", "dhahtnfxlzgb", "lhfgxabdhztn", "ftablxdghhzn", "lfhbzdathxgn", "hlfgtabxdzhn", "hxdzbantlfgh",
     "blfgzxahntdh", "lbdhfnaztxhg", "xthfaglhnzbd", "azlhgfbndthx", "ztlfdbxhahng", "axnfdhtgbhlz", "tgzdhhbalnxf",
     "xbhgzdafhnlt", "xnalfbdzgthh", "tbgdhfhlxanz", "atgnbxdflhhz", "thzgfbxladnh", "htnlbafzhxgd", "lbanhtzhxfdg",
     "ghahlztbfdxn", "azlnbhhtfdgx", "ndagbzthfhlx", "hgandbtfzxlh", "hadtfxhbgznl", "hlxzfghndatb", "xbhahfngtzld",
     "ndtagzlfhbhx", "glxzfhntbdha", "ltdhbafgxhnz", "dhafntlghbzx", "lnafgtzbdxhh", "bhndalgxztfh", "gldbzfahxhnt",
     "ntzblgadhhxf", "dhlbgxnzfhat", "fdhngaxzlhbt", "nghtfdalbzxh", "hgfdbalzhtnx", "hafnhxtzlbdg", "zhgxbtfhnlda",
     "lzbnadfghxht", "lxtazgnhfbdh", "lhnfabhtdgxz", "ftxzhanbldgh", "xbgfaztdhlnh", "zbatlxnhdfgh", "zdxhnlfghtba",
     "adtglnbhxfzh", "afthznglhxbd", "bxnghhdtazfl", "lxdzthbfngha", "hxzlntadfghb", "hfxtghdnzlab", "zhgfhndtalbx",
     "talzxngfbdhh", "hnhxfldgbatz", "nlxgzhadhbtf", "bzdhaltnfghx", "zbhnxfdglhta", "xfagtnlhzbhd", "nhghzlxtdbfa",
     "hxdzbantflgh", "gfnhhbtlzdxa", "bdfzngxlthha", "hnagzfbhdtxl", "dfbzlnhgxaht", "nflgtxdahbhz", "hdabtfzxgnhl",
     "ftlhzbhanxdg", "lfgazbdxhtnh", "dbnfhxhlatzg", "nhhaxftzdblg", "flhnxztdbhga", "hgzhntaxdflb", "anflzhxgbhdt",
     "gbzxatdhlfhn", "lbxhadnthgfz", "tdhfhazlbgnx", "tnhdbhalgfzx", "nxagftdlhbhz", "fdahtbhznxlg", "lthzxbdhgnaf",
     "hahxnlfdzbgt", "ndfthalzghbx", "bghndxfhazlt", "xdhzgbalntfh", "tznxhdfhlagb", "ghlhaztbfdxn", "hlnghbfzxdat",
     "bhxdzahglfnt", "ntxhlbahdzfg", "xgbafnhztdlh", "ldfgztbhnxha", "xzadhlhtbfng", "hbxzdtnahlgf", "thflnhbaxgdz",
     "dbhhxtgzfnal", "anghxzfhtdlb", "agfhhxdztbln", "txbahnghzfdl", "xafgzthlbhnd", "txlhndagzbfh", "zldngaxhbhft",
     "xfzlbgtnhhda", "dhxtanhgblzf", "tnhdblhfazxg", "ldgtznbfahxh", "nbhxlgfdtahz", "hflnhxazgdtb", "gtlzadnhfxbh",
     "ngltfdahbzxh", "abtfxlnhdhzg", "ntlfhdazbxhg", "blfdzgtnhahx", "hdhntxlbazgf", "dfnghzbtlhxa", "nhlgadzthxbf",
     "hgdbtlhxznaf", "zxghdlnhaftb", "tgxhhfbznlad", "zhtnfdabglxh", "xtlzadnhfgbh", "xtdlbnfhahgz", "gzfntbdlxhha",
     "agdhzhlxtbfn", "nhlbzhxdftga", "zxfthbghndla", "bhnxlfahdgtz", "hhdnxabfgltz", "hgzhdtaxnflb", "zxhbfadngtlh",
     "tgdxafbzlhnh", "tgnxhdfhlazb", "abtghhdfxlzn", "hxdnafzbghlt", "xladhbngftzh", "ntglhadhbfxz", "ngdxlzhahfbt",
     "zxahtndfhglb", "hdlaghfbtnxz", "glznatfhxhdb", "hnhzgdxaftlb", "hlgdtxbaznhf", "ahzgfxnlhtdb", "xzhhbgandlft",
     "zlxhbngtdhaf", "xfnhalgzhtdb", "gbftxdlzahhn", "gfhlxbadznth", "bzlahdntfxgh", "bhaldftzghxn", "ldtzagnhxfhb",
     "lnzfgtabdxhh", "xntdgzhhalbf", "xzdtalhnfghb", "xabdnhlzgfth", "hxnzlbftdgah", "zdxltnghahbf", "nfhthgxzabdl",
     "dhzfnbxghlta", "nzlxhahtbdgf", "zhdtanlfbghx", "thhlbzgdnxaf", "ghnlbtaxhdfz", "axnfdltgbhhz", "bnhthdglfxza",
     "bzdtalhnfghx", "xhdzntgblahf", "ndhgzbftlahx", "bxhnglazfthd", "fldgtbxnazhh", "gtabxhdnhflz", "zgbnltahfhdx",
     "ahtznxbglfdh", "fhazblxgtdnh", "fbgdazhtlnhx", "thzdfbxlagnh", "gblaxzfhtndh", "fghzbnhdlxat", "ntagfxdlhbhz",
     "fdzhhbngaxlt", "zdgfxnhalhbt", "zbfglhnhdaxt", "angtdzhbflhx", "tdhfxglanzhb", "agtznxbhlfdh", "fzhnbxlthadg",
     "xabzlgndhthf", "bhndhlgxztfa", "agfdnlxhtzbh", "zlfthaxhbngd", "fadglhzxtbhn", "hfngtdhalxbz", "hdhlazxfbntg",
     "hzblnftdagxh", "gzbntdlfhxah", "txlhfdagzbnh", "hxfbdhltangz", "gatnfhhdbzxl", "bzdgxtafhnhl", "ahxhzfndtbgl"]

solution = Solution()
print(solution.numSimilarGroups(A))
