#!/usr/bin/env python

import mechanize
import os
from subprocess import call


url = "http://172.16.16.16/24online/webpages/client.jsp?fromlogout=true"

br = mechanize.Browser()
br.open(url)

br.select_form(name='clientloginform')

try:
	br.form.find_control('username1')

except:
	br.form['username'] = ''
	br.form['password'] = ''
	br.submit()


os.system("google-chrome http://172.16.16.16/24online/webpages/client.jsp?fromlogout=true")
