"""fixed circular foriegn key typo

Revision ID: c3fdaccf9d8f
Revises: f6b1e8472a49
Create Date: 2021-03-03 03:09:22.499021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fdaccf9d8f'
down_revision = 'f6b1e8472a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folders_category_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key('folders_category_id_fkey', 'folders', 'users', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
