"""updating file relationships

Revision ID: bb0e1c09c749
Revises: 605401edec5b
Create Date: 2021-03-04 00:15:01.355807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0e1c09c749'
down_revision = '605401edec5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_tag', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('file_tag', sa.Column('file_id', sa.Integer(), nullable=False))
    op.add_column('file_tag', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.add_column('file_tag', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'file_tag', 'files', ['file_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'file_tag', 'tags', ['tag_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('file_tag', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_tag', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file_tag', type_='foreignkey')
    op.drop_constraint(None, 'file_tag', type_='foreignkey')
    op.drop_column('file_tag', 'updated_at')
    op.drop_column('file_tag', 'tag_id')
    op.drop_column('file_tag', 'file_id')
    op.drop_column('file_tag', 'created_at')
    # ### end Alembic commands ###
