"""fixed relationship of file and folder

Revision ID: 605401edec5b
Revises: c3fdaccf9d8f
Create Date: 2021-03-03 03:11:41.601553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605401edec5b'
down_revision = 'c3fdaccf9d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('folder_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'folder_id')
    # ### end Alembic commands ###
