version: "3"
services:
  db:
    image: postgres
    # set up a volume so our database info persists
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    # building our own docker image
    build:
      context: .
      dockerfile: Dockerfile.web
    # name our image
    image: richierob/pokedex-web
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      # setting up a dependency on our database container
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  frontend:
    # building our own docker image
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: richierob/pokedex-frontend
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development