#!/bin/bash

##
## colors defs in bash shell 
#  example
## echo -e "${COLOR_RED}Error!${COLOR_REMOVE} Error message..."
##

COLOR_BLACK='\033[0;30m'
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_BROWN='\033[0;33m'
COLOR_BLUE='\033[0;34m'
COLOR_PURPLE='\033[0;35m'
COLOR_CYAN='\033[0;36m'
COLOR_LIGHT_GRAY='\033[0;37m'
COLOR_DARK_GRAY='\033[1;30m'
COLOR_LIGHT_RED='\033[1;31m'
COLOR_LIGHT_GREEN='\033[1;32m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[1;34m'
COLOR_LIGHT_PURPLE='\033[1;35m'
COLOR_LIGHT_CYAN='\033[1;36m'
COLOR_WHITE='\033[1;37m'
COLOR_REMOVE='\033[0m'


function checkarg() {
    ARG_ACTUAL_COUNT=$1
    ARG_REQUIRED_COUNT=$2
    FUNCTION_CALLED=$3
    ERROR_MESSAGE=$4

    if [ $ARG_ACTUAL_COUNT -lt $ARG_REQUIRED_COUNT ]; then
        echo -e "${COLOR_RED}$FUNCTION_CALLED${COLOR_REMOVE}: ${ERROR_MESSAGE}";
        
    fi
}


#example 
#checkarg $# 2 "Examplecommand" "Please specify at least 2 arguments: [source, destination]"




