export const ADD_STRAINSELECTION = 'ADD_STRAINSELECTION';
export const DELETE_STRAINSELECTION = 'DELETE_STRAINSELECTION';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

