alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias lookupip="dig +short"
alias open-ports="sudo lsof -i -P -n | grep LISTEN"
alias open-ports="sudo ss -tulpn -o state listening"
alias open-ports="sudo ss -tulpn"
