# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!([
  { username: "deveronheartbeat" },
  { username: "mainetreasure" },
  { username: "imageband" },
  { username: "holdbusload" },
  { username: "remixsuperbowl" },
  { username: "pluckbower" },
  { username: "phonytidbit" },
  { username: "unmovingdean" },
  { username: "throatedundivided" },
  { username: "vietnamesestitch" },
  { username: "arsonistmoderato" },
  { username: "yoyoroman" },
  { username: "yesterdaypledge" },
  { username: "englandcarbine" },
  { username: "melvillesoncup" },
  { username: "kabobreoccur" },
  { username: "placereduce" },
  { username: "afterguardwithey" },
  { username: "passablechewing" },
  { username: "exorcismpastebin" },
  { username: "washedelephant" },
  { username: "blackwaterfair" },
  { username: "peanutunified" },
  { username: "pueblouranus" },
  { username: "marxismapplause" },
  { username: "internshipmorals" },
  { username: "imaginableimpaired" },
  { username: "cadillacsane" },
  { username: "gravyminus" },
  { username: "potatojavelin" },
  { username: "youthscapegratified" },
  { username: "impetuousriver" },
  { username: "thrandabject" },
  { username: "sabdengrandfather" },
  { username: "wantingcortex" },
  { username: "bureaucratsnack" },
  { username: "sierrastanhope" },
  { username: "coupleoccupier" },
  { username: "purposealbert" },
  { username: "managerialcolgate" },
  { username: "sparklingmousy" },
  { username: "addadauphine" },
  { username: "lumpishpanty" },
  { username: "raiderupright" },
  { username: "invitationsmashup" },
  { username: "traypolly" },
  { username: "alexandriasneeze" },
  { username: "laviniapipet" },
  { username: "ceilingeleonora" },
  { username: "pilotbikini" },
  { username: "dangopoynton" },
  { username: "donskinning" },
  { username: "darkenedpickled" },
  { username: "depressedcolony" },
  { username: "badgercoziness" },
  { username: "willedupstream" },
  { username: "linnetcrossed" },
])

Poll.create!([
  { author_id: 13, title: "Colors" },
  { author_id: 20, title: "Health" },
  { author_id: 23, title: "Fast Food Joints" },
  { author_id: 50, title: "Web Frameworks" },

])

Question.create!([
  { poll_id: 1, text: "What is your favorite color?" },
  { poll_id: 1, text: "Do you consider blue warm or cold?" },
  { poll_id: 2, text: "Do you consider yourself healty?" },
  { poll_id: 2, text: "How often do you visit your doctor?" },
  { poll_id: 3, text: "What is your favorite fast food chain?" },
  { poll_id: 3, text: "Do you prefer fried chicken from KFC or Popeyes" },
  { poll_id: 4, text: "What is your favorite web framework?" },
  { poll_id: 4, text: "Which framework do you want to learn?" },

])

AnswerChoice.create!([
  { question_id: 1, text: "Red" },
  { question_id: 1, text: "Blue" },
  { question_id: 1, text: "White" },
  { question_id: 1, text: "Green" },
  { question_id: 2, text: "Warm" },
  { question_id: 2, text: "Cold" },
  { question_id: 3, text: "Yes" },
  { question_id: 3, text: "No" },
  { question_id: 4, text: "< 1/month" },
  { question_id: 4, text: "Never" },
  { question_id: 4, text: "1/week" },
  { question_id: 5, text: "McDonalds" },
  { question_id: 5, text: "Taco Bell" },
  { question_id: 5, text: "Wendy's" },
  { question_id: 5, text: "Subway" },
  { question_id: 6, text: "KFC" },
  { question_id: 6, text: "Popeyes" },
  { question_id: 7, text: "Rails" },
  { question_id: 7, text: "React" },
  { question_id: 7, text: "Angular" },
  { question_id: 7, text: "Django" },
  { question_id: 8, text: "Rails" },
  { question_id: 8, text: "React" },
  { question_id: 8, text: "Angular" },
  { question_id: 8, text: "Django" },
])

Response.create!([
  { user_id: 2, answer_choice_id: 2 },
  { user_id: 2, answer_choice_id: 5 },
  { user_id: 2, answer_choice_id: 8 },
  { user_id: 14, answer_choice_id: 4 },
  { user_id: 14, answer_choice_id: 6 },
  { user_id: 14, answer_choice_id: 12 },
  { user_id: 23, answer_choice_id: 10 },
  { user_id: 23, answer_choice_id: 17 },
  { user_id: 35, answer_choice_id: 8 },
])
