"""added content field to files

Revision ID: bd666003f900
Revises: acb7ddf4d2bb
Create Date: 2021-03-09 09:20:45.401831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd666003f900'
down_revision = 'acb7ddf4d2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('content', sa.Text(), nullable=True))
    op.alter_column('files', 's3_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 's3_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('files', 'content')
    # ### end Alembic commands ###
