"""fixed to_dict method for folder.category

Revision ID: acb7ddf4d2bb
Revises: bb0e1c09c749
Create Date: 2021-03-04 00:20:11.649718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb7ddf4d2bb'
down_revision = 'bb0e1c09c749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_file_tag_id_fkey', 'files', type_='foreignkey')
    op.drop_column('files', 'file_tag_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_tag_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('files_file_tag_id_fkey', 'files', 'file_tag', ['file_tag_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
